### ISSUE TITLE
Title on every page

### ISSUE THREAD

**Issue by aayushkothari11** [djunicode/DJ-Comps-Student-Info-Portal#65]
Change titles and favicon(if needed)

**Comment by Kushald2805** [comment]
Yeh karna hai ki nai?

**Comment by aayushkothari11** [comment]
Do this. Sab pe UNICODE hi hai title mostly

**Comment by Kushald2805** [comment]
Haa. I will change it according to the page then.

**Comment by shahsaumya** [comment]
Finish this off and we are done for all the high priority stuff! @Kushald2805

**Comment by Kushald2805** [comment]
I was working on issue#80 because this won't require much time.
