### ISSUE TITLE
Edit image

### ISSUE THREAD

**Issue by aayushkothari11** [djunicode/DJ-Comps-Student-Info-Portal#80]
![screenshot from 2018-09-16 17-49-50](https://user-images.githubusercontent.com/29770201/45596576-677cab00-b9db-11e8-8afe-3d585b60e858.png)
![screenshot from 2018-09-16 17-49-54](https://user-images.githubusercontent.com/29770201/45596577-677cab00-b9db-11e8-93d2-75c0c3f50669.png)

Another frontend size issue.
Also there is no seperator between 2 projects.
Same for internships, hackathons etc

**Comment by shahsaumya** [comment]
Is this going to be worked on @aayushkothari11?

**Comment by aayushkothari11** [comment]
I guess this is important as teacher would want to see certificates and stuff. From the image that i have uploaded in issues it is clear that certificate or any picture wont be proper or full.
The one which i had opened last night which was along the same lines for different pages like hackathons etc was not that important.
your call @shahsaumya on this

**Comment by shahsaumya** [comment]
Okay cool. Will have to work on this then.

**Comment by aayushkothari11** [comment]
This still exists @Kushald2805. Try making a virtualenv, I have added commands in the readme for that.
